Repository KH-Q-peaker/project-wego, pull requests merged in 2023-04, with the labels that each got.

#7 img 파일 이름 수정 및 기본틀 만듦
  src/main/java/org/zerock/wego/controller/HomeController.java
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/views/badge/badge.jsp
  src/main/webapp/WEB-INF/views/common/footer.jsp
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/img/WegoBG.png
  src/main/webapp/resources/img/WegoLogo.png
  src/main/webapp/resources/img/WegoLogoSan.png
  src/main/webapp/resources/img/WegoLogoSun.png
  src/main/webapp/resources/img/WegoTitle.png
  src/main/webapp/resources/js/badge.js
Labels: 👾버그, 🖼프론트엔드, 🛠 Refactoring, UI, ✨중요

#9 test입니다.
  src/main/webapp/resources/css/test.css
Labels: 📝Docs, UI

#11 [docs] PR 탬플릿 샘플입니다.
  .github/pull_request_template.md
Labels: 📝Docs

#12 [test] PR 탬플릿 테스트중입니다.
  src/main/webapp/resources/css/test.css
Labels: 🗜테스트

#14 fix: 메인페이지(검색기능 외)구현(좋아요는 회원ID 9기준으로 구현)
  src/main/java/org/zerock/wego/controller/HomeController.java
  src/main/java/org/zerock/wego/controller/MainController.java
  src/main/java/org/zerock/wego/domain/FavoriteDTO.java
  src/main/java/org/zerock/wego/domain/FavoriteVO.java
  src/main/java/org/zerock/wego/domain/FileDTO.java
  src/main/java/org/zerock/wego/domain/FileVO.java
  src/main/java/org/zerock/wego/domain/MountainInfoViewVO.java
  src/main/java/org/zerock/wego/domain/RecruitmentDTO.java
  src/main/java/org/zerock/wego/domain/RecruitmentVO.java
  src/main/java/org/zerock/wego/domain/RecruitmentViewVO.java
  src/main/java/org/zerock/wego/domain/ReviewDTO.java
  src/main/java/org/zerock/wego/domain/ReviewVO.java
  src/main/java/org/zerock/wego/domain/ReviewViewVO.java
  src/main/java/org/zerock/wego/exception/ControllerException.java
  src/main/java/org/zerock/wego/exception/ServiceException.java
  src/main/java/org/zerock/wego/mapper/FavoriteMapper.java
  src/main/java/org/zerock/wego/mapper/MountainInfoMapper.java
  src/main/java/org/zerock/wego/mapper/RecruitmentMapper.java
  src/main/java/org/zerock/wego/mapper/ReviewMapper.java
  src/main/java/org/zerock/wego/service/FavoriteService.java
  src/main/java/org/zerock/wego/service/FavoriteServiceImpl.java
  src/main/java/org/zerock/wego/service/MountainInfoService.java
  src/main/java/org/zerock/wego/service/MountainInfoServiceImpl.java
  src/main/java/org/zerock/wego/service/RecruitmentService.java
  src/main/java/org/zerock/wego/service/RecruitmentServiceImpl.java
  src/main/java/org/zerock/wego/service/ReviewService.java
  src/main/java/org/zerock/wego/service/ReviewServiceImpl.java
  src/main/resources/org/zerock/wego/mapper/FavoriteMapper.xml
  src/main/resources/org/zerock/wego/mapper/MountainInfoMapper.xml
  src/main/resources/org/zerock/wego/mapper/RecruitmentMapper.xml
  src/main/resources/org/zerock/wego/mapper/ReviewMapper.xml
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/resources/js/header.js
  src/main/webapp/resources/js/main.js
Labels: 백엔드, 🎉FEAT, 🖼프론트엔드, UI, 🔍Review Required, ✨중요

#16 test 입니다.
  src/main/webapp/resources/css/ingutest.css
  test
Labels: 🗜테스트

#20 style:nav 두줄로 나타나는 현상 수정한다.
  src/main/webapp/resources/css/header.css
Labels: UI

#23 docs: .properties 파일 수정에 따른 root.xml파일을 변경한다
  src/main/webapp/WEB-INF/spring/root-context.xml
Labels: 📝Docs, ✨중요

#24 feat : Review Mapper, Service 은혜님과 병합, Controller 추가
  src/main/java/org/zerock/wego/controller/ReviewController.java
  src/main/java/org/zerock/wego/domain/CommentDTO.java
  src/main/java/org/zerock/wego/mapper/ReviewMapper.java
  src/main/java/org/zerock/wego/service/ReviewService.java
  src/main/java/org/zerock/wego/service/ReviewServiceImpl.java
  src/main/resources/org/zerock/wego/mapper/ReviewMapper.xml
  src/main/webapp/WEB-INF/views/comment/comment.jsp
  src/main/webapp/WEB-INF/views/comment/load.jsp
Labels: 백엔드, 🎉FEAT

#27 feat : 카카오 로그인 구현. 세션의 auth에 따라 헤더 로그인 버튼 노출
  src/main/java/org/zerock/wego/controller/AuthController.java
  src/main/java/org/zerock/wego/controller/LoginController.java
  src/main/java/org/zerock/wego/controller/UserController.java
  src/main/java/org/zerock/wego/domain/UserDTO.java
  src/main/java/org/zerock/wego/domain/UserVO.java
  src/main/java/org/zerock/wego/domain/oauth/kakao/KakaoOAuthTokenDTO.java
  src/main/java/org/zerock/wego/domain/oauth/kakao/KakaoUserInfoDTO.java
  src/main/java/org/zerock/wego/domain/oauth/kakao/KakaoUserInfoKakaoAccount.java
  src/main/java/org/zerock/wego/domain/oauth/kakao/KakaoUserInfoProfile.java
  src/main/java/org/zerock/wego/domain/oauth/kakao/KakaoUserInfoProperties.java
  src/main/java/org/zerock/wego/exception/ControllerException.java
  src/main/java/org/zerock/wego/exception/ServiceException.java
  src/main/java/org/zerock/wego/interceptor/AuthInterceptor.java
  src/main/java/org/zerock/wego/mapper/UserMapper.java
  src/main/java/org/zerock/wego/oauth/KakaoOAuth.java
  src/main/java/org/zerock/wego/service/KakaoService.java
  src/main/java/org/zerock/wego/service/UserLoginService.java
  src/main/java/org/zerock/wego/service/UserService.java
  src/main/java/org/zerock/wego/service/UserServiceImpl.java
  src/main/resources/org/zerock/wego/mapper/UserMapper.xml
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/common/login.jsp
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/resources/js/header.js
Labels: 📝Docs, 백엔드, 🎉FEAT, 🖼프론트엔드, UI, ✨중요

#28 docs : servlet-context.xml 테스트 주석 추가
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
Labels: 📝Docs

#29 refactor : 은혜님과 Party 관련 클래스 병합 + 일부 작명 변경
  src/main/java/org/zerock/wego/controller/MainController.java
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/controller/ReviewController.java
  src/main/java/org/zerock/wego/controller/SearchController.java
  src/main/java/org/zerock/wego/domain/CommentDTO.java
  src/main/java/org/zerock/wego/domain/CommentViewVO.java
  src/main/java/org/zerock/wego/domain/PageInfo.java
  src/main/java/org/zerock/wego/mapper/CommentMapper.java
  src/main/java/org/zerock/wego/mapper/JoinMapper.java
  src/main/java/org/zerock/wego/mapper/PartyMapper.java
  src/main/java/org/zerock/wego/service/CommentService.java
  src/main/java/org/zerock/wego/service/JoinService.java
  src/main/java/org/zerock/wego/service/PartyService.java
  src/main/resources/org/zerock/wego/mapper/PartyMapper.xml
  src/main/webapp/WEB-INF/views/comment/comment.jsp
  src/main/webapp/WEB-INF/views/comment/load.jsp
  src/main/webapp/WEB-INF/views/comment/reply.jsp
  src/main/webapp/WEB-INF/views/party/detail.jsp
Labels: 백엔드, 🛠 Refactoring

#32 refactor : 누락된 CommentController 및 xml파일 추가
  src/main/java/org/zerock/wego/controller/CommentController.java
  src/main/java/org/zerock/wego/service/CommentService.java
  src/main/resources/org/zerock/wego/mapper/CommentMapper.xml
  src/main/resources/org/zerock/wego/mapper/JoinMapper.xml
  src/main/webapp/WEB-INF/views/comment/comment.jsp
  src/main/webapp/WEB-INF/views/comment/load.jsp
  src/main/webapp/WEB-INF/views/comment/reply.jsp
  src/main/webapp/WEB-INF/views/common/join.jsp
  src/main/webapp/WEB-INF/views/party/detail.jsp
Labels: 백엔드, 🖼프론트엔드

#34 <feat> : 신고 기능 추가 및 댓글, 모집 리팩토링
  src/main/java/org/zerock/wego/controller/CommentController.java
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/controller/ReportController.java
  src/main/java/org/zerock/wego/domain/PartyViewVO.java
  src/main/java/org/zerock/wego/domain/ReportDTO.java
  src/main/java/org/zerock/wego/mapper/CommentMapper.java
  src/main/java/org/zerock/wego/mapper/ReportMapper.java
  src/main/java/org/zerock/wego/service/CommentService.java
  src/main/java/org/zerock/wego/service/JoinService.java
  src/main/java/org/zerock/wego/service/PartyService.java
  src/main/java/org/zerock/wego/service/ReportService.java
  src/main/resources/org/zerock/wego/mapper/CommentMapper.xml
  src/main/resources/org/zerock/wego/mapper/PartyMapper.xml
  src/main/resources/org/zerock/wego/mapper/ReportMapper.xml
  src/main/webapp/WEB-INF/views/party/detail.jsp
  src/main/webapp/resources/js/delete.js
Labels: 백엔드, 🎉FEAT, 🛠 Refactoring

#39 <refactor> : 참여 기능 수정, DTO추가 (얘때문에 PartyController 참여부분 수정)
  src/main/java/org/zerock/wego/controller/CommentController.java
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/controller/ReportController.java
  src/main/java/org/zerock/wego/domain/JoinDTO.java
  src/main/java/org/zerock/wego/mapper/JoinMapper.java
  src/main/java/org/zerock/wego/mapper/ReportMapper.java
  src/main/java/org/zerock/wego/service/CommentService.java
  src/main/java/org/zerock/wego/service/JoinService.java
  src/main/java/org/zerock/wego/service/ReportService.java
  src/main/resources/org/zerock/wego/mapper/JoinMapper.xml
  src/main/resources/org/zerock/wego/mapper/ReportMapper.xml
  src/main/webapp/WEB-INF/views/comment/reply.jsp
  src/main/webapp/WEB-INF/views/party/detail.jsp
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/like.css
  src/main/webapp/resources/js/join.js
  src/main/webapp/resources/js/report.js
  src/main/webapp/resources/svg/like-off.svg
  src/main/webapp/resources/svg/like-on.svg
Labels: 백엔드, 🎉FEAT, 🖼프론트엔드, 🛠 Refactoring

#41 <fix, refactor> : 댓글 구조변경, Gson수정
  src/main/java/org/zerock/wego/controller/CommentController.java
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/controller/ReviewController.java
  src/main/java/org/zerock/wego/domain/CommentViewVO.java
  src/main/java/org/zerock/wego/mapper/CommentMapper.java
  src/main/java/org/zerock/wego/service/CommentService.java
  src/main/resources/org/zerock/wego/mapper/CommentMapper.xml
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/views/comment/comment.jsp
  src/main/webapp/WEB-INF/views/comment/load.jsp
  src/main/webapp/WEB-INF/views/comment/reply.jsp
  src/main/webapp/WEB-INF/views/party/detail.jsp
  src/main/webapp/resources/css/comment.css
  src/main/webapp/resources/css/party-detail.css
  src/main/webapp/resources/css/report.css
  src/main/webapp/resources/js/comment.js
  src/main/webapp/resources/js/delete.js
  src/main/webapp/resources/js/party-detail.js
  src/main/webapp/resources/js/scroll.js
Labels: 백엔드, 🛠 Refactoring, UI

#48 refactor: login 로직 수정 및 리팩토링, 회원가입 삭제, @Builder 를 이용한 빌더패턴 적용, 세션 설정 변경(web.xml)
  src/main/java/org/zerock/wego/config/SessionConfig.java
  src/main/java/org/zerock/wego/controller/AuthController.java
  src/main/java/org/zerock/wego/controller/LoginController.java
  src/main/java/org/zerock/wego/controller/ReportController.java
  src/main/java/org/zerock/wego/controller/SignUpController.java
  src/main/java/org/zerock/wego/controller/UserController.java
  src/main/java/org/zerock/wego/domain/UserDTO.java
  src/main/java/org/zerock/wego/interceptor/AfterLoginInterceptor.java
  src/main/java/org/zerock/wego/interceptor/AuthInterceptor.java
  src/main/java/org/zerock/wego/listener/RequestScopeAttributesListener.java
  src/main/java/org/zerock/wego/oauth/KakaoOAuth.java
  src/main/java/org/zerock/wego/service/KakaoService.java
  src/main/java/org/zerock/wego/service/LoginService.java
  src/main/java/org/zerock/wego/service/OAuthService.java
  src/main/java/org/zerock/wego/service/UserService.java
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/views/common/signup.jsp
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/resources/js/signup.js
Labels: 📝Docs, 백엔드, 🛠 Refactoring

#50 <feat, refactor> : 유저 프로필 이동 추가, 코드 컨벤션
  src/main/java/org/zerock/wego/aop/LogAdvice.java
  src/main/java/org/zerock/wego/controller/CommentController.java
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/controller/ReviewController.java
  src/main/java/org/zerock/wego/domain/JoinDTO.java
  src/main/java/org/zerock/wego/domain/PageInfo.java
  src/main/java/org/zerock/wego/mapper/FavoriteMapper.java
  src/main/java/org/zerock/wego/mapper/FileMapper.java
  src/main/java/org/zerock/wego/mapper/JoinMapper.java
  src/main/java/org/zerock/wego/mapper/ReportMapper.java
  src/main/java/org/zerock/wego/service/CommentService.java
  src/main/java/org/zerock/wego/service/FavoriteService.java
  src/main/java/org/zerock/wego/service/FileService.java
  src/main/java/org/zerock/wego/service/JoinService.java
  src/main/java/org/zerock/wego/service/PartyService.java
  src/main/java/org/zerock/wego/service/ReportService.java
  src/main/resources/org/zerock/wego/mapper/CommentMapper.xml
  src/main/resources/org/zerock/wego/mapper/FavoriteMapper.xml
  src/main/resources/org/zerock/wego/mapper/FileMapper.xml
  src/main/resources/org/zerock/wego/mapper/ReportMapper.xml
  src/main/webapp/WEB-INF/views/comment/comment.jsp
  src/main/webapp/WEB-INF/views/comment/load.jsp
  src/main/webapp/WEB-INF/views/comment/reply.jsp
  src/main/webapp/WEB-INF/views/common/alert.jsp
  src/main/webapp/WEB-INF/views/party/detail.jsp
  src/main/webapp/WEB-INF/views/review/detail.jsp
  src/main/webapp/resources/css/default.css
  src/main/webapp/resources/js/comment.js
  src/main/webapp/resources/js/delete.js
  src/main/webapp/resources/js/party-detail.js
Labels: 백엔드, 🎉FEAT, 🛠 Refactoring

#51 ﻿style:게시글 목록 글자수 제한설정
  src/main/webapp/WEB-INF/views/profile/comment.jsp
Labels: 🖼프론트엔드, UI

#52 feat: 게시판 기능 추가
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/controller/ReviewController.java
  src/main/java/org/zerock/wego/controller/SanInfoController.java
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/info/info.jsp
  src/main/webapp/WEB-INF/views/party/party.jsp
  src/main/webapp/WEB-INF/views/review/review.jsp
  src/main/webapp/resources/css/partyItem.css
  src/main/webapp/resources/css/remote.css
  src/main/webapp/resources/css/reviewItem.css
  src/main/webapp/resources/css/sanInfoItem.css
  src/main/webapp/resources/css/sort.css
  src/main/webapp/resources/js/sort.js
  src/main/webapp/resources/svg/add-item.svg
  src/main/webapp/resources/svg/arrow.svg
Labels: 백엔드, 🖼프론트엔드, UI

#54 <refactor> : boolean 변수명 (과거형 -> 현재형 변경)
  src/main/java/org/zerock/wego/aop/LogAdvice.java
  src/main/java/org/zerock/wego/controller/CommentController.java
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/controller/ReportController.java
  src/main/java/org/zerock/wego/controller/ReviewController.java
  src/main/java/org/zerock/wego/mapper/FileMapper.java
  src/main/java/org/zerock/wego/service/CommentService.java
  src/main/java/org/zerock/wego/service/FileService.java
  src/main/java/org/zerock/wego/service/JoinService.java
  src/main/java/org/zerock/wego/service/PartyService.java
  src/main/java/org/zerock/wego/service/ReportService.java
  src/main/java/org/zerock/wego/service/ReviewService.java
  src/main/webapp/resources/css/party-detail.css
  src/main/webapp/resources/css/review-detail.css
  src/main/webapp/resources/js/report.js
Labels: 🛠 Refactoring

#56 [refactor] : @Param 이슈해결
  src/main/java/org/zerock/wego/mapper/ProfileMapper.java
  src/main/webapp/WEB-INF/views/profile/userposts.jsp
  src/main/webapp/resources/css/userposts.css
  src/main/webapp/resources/img/leaf.png
Labels: 백엔드, 🛠 Refactoring

#60 style : header.jsp / feat : badge
  src/main/java/org/zerock/wego/config/BadgeConfig.java
  src/main/java/org/zerock/wego/controller/BadgeController.java
  src/main/java/org/zerock/wego/domain/BadgeGetDTO.java
  src/main/java/org/zerock/wego/domain/BadgeGetVO.java
  src/main/java/org/zerock/wego/domain/BadgeVO.java
  src/main/java/org/zerock/wego/interceptor/AfterLoginInterceptor.java
  src/main/java/org/zerock/wego/mapper/BadgeGetMapper.java
  src/main/java/org/zerock/wego/mapper/BadgeMapper.java
  src/main/java/org/zerock/wego/service/BadgeGetService.java
  src/main/java/org/zerock/wego/service/BadgeService.java
  src/main/resources/org/zerock/wego/mapper/BadgeGetMapper.xml
  src/main/resources/org/zerock/wego/mapper/BadgeMapper.xml
  src/main/webapp/WEB-INF/views/badge/badge.jsp
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/resources/css/badge.css
  src/main/webapp/resources/img/badgeTitle.svg
  src/main/webapp/resources/img/rank1st.svg
  src/main/webapp/resources/img/rank2nd.svg
  src/main/webapp/resources/img/rank3rd.svg
  src/main/webapp/resources/img/rankTilte.svg
  src/main/webapp/resources/img/ranking.svg
  src/main/webapp/resources/img/setting.svg
  src/main/webapp/resources/js/badge.js
Labels: 백엔드, 🎉FEAT, 🖼프론트엔드, UI

#63 style:신고이름변경 버튼크기변경/충돌변경
  src/main/webapp/WEB-INF/views/profile/userpage.jsp
  src/main/webapp/resources/css/userpageindex.css
  src/main/webapp/resources/js/favorite.js
Labels: 👾버그, 🖼프론트엔드

#64 <feat, refactor> : 유저신고 추가, 에러페이지 추가, 작명 변경
  src/main/java/org/zerock/wego/controller/CommentController.java
  src/main/java/org/zerock/wego/controller/ExceptionController.java
  src/main/java/org/zerock/wego/service/CommentService.java
  src/main/webapp/WEB-INF/views/error.jsp
  src/main/webapp/WEB-INF/views/error/notFoundPage.jsp
  src/main/webapp/resources/css/error.css
  src/main/webapp/resources/img/error.png
  src/main/webapp/resources/js/comment.js
  src/main/webapp/resources/js/report.js
Labels: 🎉FEAT, 🛠 Refactoring

#65 feat, refactor : Coding Convention에 맞게 Refactoring, 글 작성 및 수정 시 이동 경로 변경
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/controller/SearchController.java
  src/main/java/org/zerock/wego/domain/FileDTO.java
  src/main/java/org/zerock/wego/service/FileService.java
  src/main/java/org/zerock/wego/service/PartyService.java
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/resources/js/party-register.js
  src/main/webapp/resources/js/review-register.js
Labels: 백엔드, 🎉FEAT, 🖼프론트엔드, 🛠 Refactoring

#66 <feat> : 게시판상세글방문시 조회수증가기능추가
  src/main/java/org/zerock/wego/domain/ProfileVO.java
  src/main/java/org/zerock/wego/mapper/PartyMapper.java
  src/main/java/org/zerock/wego/mapper/ReviewMapper.java
  src/main/java/org/zerock/wego/service/PartyService.java
  src/main/java/org/zerock/wego/service/ReviewService.java
  src/main/resources/org/zerock/wego/mapper/PartyMapper.xml
  src/main/resources/org/zerock/wego/mapper/ProfileMapper.xml
  src/main/resources/org/zerock/wego/mapper/ReviewMapper.xml
  src/main/webapp/WEB-INF/views/profile/comment.jsp
  src/main/webapp/WEB-INF/views/profile/userpage.jsp
  src/main/webapp/WEB-INF/views/profile/userposts.jsp
  src/main/webapp/resources/css/usercomment.css
  src/main/webapp/resources/css/userposts.css
  src/main/webapp/resources/js/paging.js
Labels: 백엔드, 🎉FEAT, 🖼프론트엔드

#69 feat,refactor : badge 대표뱃지 설정 기능 추가 및 공통부분 수정 / 리팩토링 진행중
  pom.xml
  src/main/java/org/zerock/wego/aop/LogAdvice.java
  src/main/java/org/zerock/wego/config/BadgeConfig.java
  src/main/java/org/zerock/wego/controller/AuthController.java
  src/main/java/org/zerock/wego/controller/BadgeController.java
  src/main/java/org/zerock/wego/controller/UserController.java
  src/main/java/org/zerock/wego/domain/BadgeGetVO.java
  src/main/java/org/zerock/wego/mapper/BadgeGetMapper.java
  src/main/java/org/zerock/wego/mapper/BadgeMapper.java
  src/main/java/org/zerock/wego/service/BadgeGetService.java
  src/main/java/org/zerock/wego/service/BadgeService.java
  src/main/java/org/zerock/wego/service/FileService.java
  src/main/java/org/zerock/wego/service/LoginService.java
  src/main/java/org/zerock/wego/service/UserService.java
  src/main/resources/org/zerock/wego/mapper/BadgeGetMapper.xml
  src/main/resources/org/zerock/wego/mapper/BadgeMapper.xml
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/views/badge/badge.jsp
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/profile/userpage.jsp
  src/main/webapp/resources/css/badge.css
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/js/badge.js
  src/main/webapp/resources/js/footer.js
  src/main/webapp/resources/js/header.js
Labels: 📝Docs, 백엔드, 🎉FEAT, 🖼프론트엔드, 🛠 Refactoring, UI, ✨중요

#74 <feat, refactor> : Party 일부 예외 추가, JoinController 다시 합침
  src/main/java/org/zerock/wego/controller/CommentController.java
  src/main/java/org/zerock/wego/controller/JoinController.java
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/mapper/CommentMapper.java
  src/main/java/org/zerock/wego/mapper/PartyMapper.java
  src/main/java/org/zerock/wego/mapper/ReportMapper.java
  src/main/java/org/zerock/wego/service/common/CommentService.java
  src/main/java/org/zerock/wego/service/common/ReportService.java
  src/main/java/org/zerock/wego/service/party/PartyService.java
  src/main/java/org/zerock/wego/service/review/ReviewService.java
  src/main/resources/org/zerock/wego/mapper/CommentMapper.xml
  src/main/resources/org/zerock/wego/mapper/PartyMapper.xml
  src/main/resources/org/zerock/wego/mapper/ReportMapper.xml
  src/main/webapp/resources/js/comment.js
  src/main/webapp/resources/js/join.js
Labels: 🎉FEAT, 🛠 Refactoring

#75 <feat> mypage추가
  src/main/java/org/zerock/wego/controller/ProfileController.java
  src/main/java/org/zerock/wego/mapper/ProfileMapper.java
  src/main/java/org/zerock/wego/service/profile/ProfileService.java
  src/main/resources/org/zerock/wego/mapper/ProfileMapper.xml
  src/main/webapp/WEB-INF/views/mypage/availableParty.jsp
  src/main/webapp/WEB-INF/views/mypage/footer.jsp
  src/main/webapp/WEB-INF/views/mypage/head.jsp
  src/main/webapp/WEB-INF/views/mypage/header.jsp
  src/main/webapp/WEB-INF/views/mypage/myclimb.jsp
  src/main/webapp/WEB-INF/views/mypage/myinfo.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
  src/main/webapp/WEB-INF/views/mypage/mypageContainer.jsp
  src/main/webapp/WEB-INF/views/mypage/mytext.html
  src/main/webapp/WEB-INF/views/mypage/mytext.jsp
  src/main/webapp/WEB-INF/views/mypage/nickname.jsp
  src/main/webapp/WEB-INF/views/mypage/pastParty.jsp
  src/main/webapp/WEB-INF/views/profile/comment.jsp
  src/main/webapp/WEB-INF/views/profile/userpage.jsp
  src/main/webapp/WEB-INF/views/profile/userposts.jsp
  src/main/webapp/resources/css/myPageindex.css
  src/main/webapp/resources/css/myinfo.css
  src/main/webapp/resources/css/mylike.css
  src/main/webapp/resources/css/mypage.css
  src/main/webapp/resources/css/report.css
  src/main/webapp/resources/js/myinfo.js
  src/main/webapp/resources/js/mypage.js
Labels: 백엔드, 🎉FEAT, 🖼프론트엔드, UI

#77 feat : 모집 및 후기 이미지 처리 관련 로직 변경 및 비로그인 접근 시 설정 구현
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/controller/ReviewController.java
  src/main/java/org/zerock/wego/domain/common/FileDTO.java
  src/main/java/org/zerock/wego/domain/common/FileVO.java
  src/main/java/org/zerock/wego/service/common/FileService.java
  src/main/resources/org/zerock/wego/mapper/FileMapper.xml
  src/main/webapp/WEB-INF/views/review/modify.jsp
  src/main/webapp/resources/js/party-register.js
  src/main/webapp/resources/js/review-register.js
Labels: 백엔드, 🎉FEAT, 🖼프론트엔드, ✨중요

#80 doc, feat : interceptor mapping 추가, 뱃지 획득 추가
  src/main/java/org/zerock/wego/aop/LogAdvice.java
  src/main/java/org/zerock/wego/controller/BadgeController.java
  src/main/java/org/zerock/wego/mapper/BadgeGetMapper.java
  src/main/java/org/zerock/wego/service/badge/BadgeGetService.java
  src/main/java/org/zerock/wego/service/review/ReviewService.java
  src/main/resources/org/zerock/wego/mapper/BadgeGetMapper.xml
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
Labels: 📝Docs, 백엔드, 🎉FEAT, ✨중요

#81 feat : 메인페이지의 각 게시글의 이미지가 없을 때 대체 이미지 추가
  src/main/java/org/zerock/wego/domain/review/ReviewViewVO.java
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/resources/img/leaf.png
Labels: 🖼프론트엔드

#82 feat : 메인, 통합검색 페이지에 유저 프로필이 없는 경우 기본 이미지로 표시
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/WEB-INF/views/search.jsp
Labels: 🎉FEAT, 🖼프론트엔드, UI

#83 fix: interceptor mapping
  src/main/java/org/zerock/wego/interceptor/AuthInterceptor.java
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
Labels: 👾버그, 백엔드, ✨중요

#84 feat, refactor: 로그아웃 구현, header jsp, css 약간 수정, loginC refactor
  src/main/java/org/zerock/wego/aop/LogAdvice.java
  src/main/java/org/zerock/wego/controller/LoginController.java
  src/main/java/org/zerock/wego/interceptor/LogoutInterceptor.java
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/js/header.js
Labels: 📝Docs, 백엔드, 🎉FEAT, 🖼프론트엔드, ✨중요

#86 Fix: top.svg
  src/main/webapp/resources/svg/top.svg
Labels: UI

#87 <feat><refactor> 마이페이지 기능 추가 및 수정
  src/main/java/org/zerock/wego/controller/ProfileController.java
  src/main/java/org/zerock/wego/domain/profile/MyPartyVO.java
  src/main/java/org/zerock/wego/mapper/ProfileMapper.java
  src/main/java/org/zerock/wego/service/profile/ProfileService.java
  src/main/resources/org/zerock/wego/mapper/ProfileMapper.xml
  src/main/webapp/WEB-INF/views/mypage/availableParty.jsp
  src/main/webapp/WEB-INF/views/mypage/head.jsp
  src/main/webapp/WEB-INF/views/mypage/myComment.jsp
  src/main/webapp/WEB-INF/views/mypage/myLike.jsp
  src/main/webapp/WEB-INF/views/mypage/myPost.jsp
  src/main/webapp/WEB-INF/views/mypage/myinfo.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
  src/main/webapp/WEB-INF/views/mypage/mypageContainer.jsp
  src/main/webapp/WEB-INF/views/mypage/pastParty.jsp
  src/main/webapp/WEB-INF/views/profile/comment.jsp
  src/main/webapp/WEB-INF/views/profile/userposts.jsp
  src/main/webapp/resources/css/myPageindex.css
  src/main/webapp/resources/css/myinfo.css
  src/main/webapp/resources/css/mypage.css
  src/main/webapp/resources/css/mytext.css
  src/main/webapp/resources/js/myinfo.js
  src/main/webapp/resources/js/mypage.js
Labels: 🎉FEAT, 🖼프론트엔드, 🛠 Refactoring

#89 feat : 후기글 이미지 최대 5개 제한 기능 추가
  src/main/webapp/resources/js/review-register.js
Labels: 🎉FEAT, 🖼프론트엔드, ✨중요

#90 feat, fix : Ranking 기능 추가, resources/img,svg 변경에 따른 경로 변경
  src/main/java/org/zerock/wego/controller/BadgeController.java
  src/main/java/org/zerock/wego/controller/MainController.java
  src/main/java/org/zerock/wego/controller/RankingController.java
  src/main/java/org/zerock/wego/domain/ranking/RankingVO.java
  src/main/java/org/zerock/wego/mapper/RankingMapper.java
  src/main/java/org/zerock/wego/service/common/UserService.java
  src/main/java/org/zerock/wego/service/ranking/RankingService.java
  src/main/resources/org/zerock/wego/mapper/RankingMapper.xml
  src/main/webapp/WEB-INF/views/badge/badge.jsp
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/WEB-INF/views/mypage/head.jsp
  src/main/webapp/WEB-INF/views/ranking/detail.jsp
  src/main/webapp/WEB-INF/views/ranking/ranking.jsp
  src/main/webapp/resources/css/badge.css
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/main.css
  src/main/webapp/resources/css/ranking-detail.css
  src/main/webapp/resources/css/ranking.css
  src/main/webapp/resources/img/Rectangle 111.png
  src/main/webapp/resources/img/Rectangle 112.png
  src/main/webapp/resources/img/Rectangle 113.png
  src/main/webapp/resources/img/badgeset.png
  src/main/webapp/resources/img/bg-wego.png
  src/main/webapp/resources/img/profile.png
  src/main/webapp/resources/img/profileset.png
  src/main/webapp/resources/img/yellowBadge.png
  src/main/webapp/resources/img/로그아웃.png
  src/main/webapp/resources/img/맨위로.png
  src/main/webapp/resources/js/header.js
  src/main/webapp/resources/js/main.js
  src/main/webapp/resources/js/ranking-detail.js
  src/main/webapp/resources/js/ranking.js
  src/main/webapp/resources/svg/logo.svg
  src/main/webapp/resources/svg/logout-hover.svg
  src/main/webapp/resources/svg/logout.svg
  src/main/webapp/resources/svg/main-icon.svg
  src/main/webapp/resources/svg/rank1st.svg
  src/main/webapp/resources/svg/rank2nd.svg
  src/main/webapp/resources/svg/rank3rd.svg
  src/main/webapp/resources/svg/rankTilte.svg
  src/main/webapp/resources/svg/rankingBronze.svg
  src/main/webapp/resources/svg/rankingGold.svg
  src/main/webapp/resources/svg/rankingSilver.svg
Labels: 👾버그, 백엔드, 🎉FEAT, 🖼프론트엔드, 🛠 Refactoring, UI, ✨중요

#91 refactor : DB컬럼 변경으로 인한 관련 코드 수정
  src/main/java/org/zerock/wego/domain/review/ReviewViewVO.java
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/WEB-INF/views/search.jsp
Labels: 백엔드, 🛢인프라, ✨중요

#93 <refactor, feat> : 회원 활동제한 인터셉터, 댓글 삽입/삭제시 목록 재로딩 추가
  src/main/java/org/zerock/wego/controller/CommentController.java
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/controller/ReviewController.java
  src/main/java/org/zerock/wego/domain/common/CommentDTO.java
  src/main/java/org/zerock/wego/interceptor/PostInterceptor.java
  src/main/java/org/zerock/wego/mapper/CommentMapper.java
  src/main/java/org/zerock/wego/service/common/CommentService.java
  src/main/java/org/zerock/wego/service/review/ReviewService.java
  src/main/resources/org/zerock/wego/mapper/CommentMapper.xml
  src/main/webapp/WEB-INF/views/comment/comment.jsp
  src/main/webapp/WEB-INF/views/comment/load.jsp
  src/main/webapp/WEB-INF/views/comment/reply.jsp
  src/main/webapp/WEB-INF/views/common/alert.jsp
  src/main/webapp/WEB-INF/views/common/delete.jsp
  src/main/webapp/WEB-INF/views/common/join.jsp
  src/main/webapp/WEB-INF/views/common/report.jsp
  src/main/webapp/WEB-INF/views/party/detail.jsp
  src/main/webapp/WEB-INF/views/review/detail.jsp
  src/main/webapp/resources/css/comment.css
  src/main/webapp/resources/css/party-detail.css
  src/main/webapp/resources/js/comment.js
  src/main/webapp/resources/js/delete.js
  src/main/webapp/resources/js/join.js
  src/main/webapp/resources/js/party-detail.js
  src/main/webapp/resources/js/review-detail.js
Labels: 백엔드, 🎉FEAT, 🛠 Refactoring

#94 fix : 로그인 회원가입 관련 버그 수정
  src/main/java/org/zerock/wego/controller/LoginController.java
  src/main/java/org/zerock/wego/domain/common/UserDTO.java
  src/main/java/org/zerock/wego/oauth/NaverOAuth.java
  src/main/java/org/zerock/wego/service/oauth/OAuthService.java
Labels: 👾버그, 백엔드, ✨중요

#96 feat : 후기 및 모집 글 작성, 수정에 대한 데이터 유효성 검증 코드 추가
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/controller/ReviewController.java
  src/main/java/org/zerock/wego/verification/PartyValidator.java
  src/main/java/org/zerock/wego/verification/ReviewValidator.java
  src/main/webapp/resources/css/search.css
  src/main/webapp/resources/js/party-register.js
  src/main/webapp/resources/js/review-register.js
Labels: 백엔드, 🎉FEAT, 🖼프론트엔드, 🛠 Refactoring, UI, ✨중요

#98 <refactor, feat> : 댓글/멘션 총합 갱신 부분 수정 , 활동제한 인터셉터 수정
  src/main/java/org/zerock/wego/controller/CommentController.java
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/controller/ReviewController.java
  src/main/java/org/zerock/wego/interceptor/PostInterceptor.java
  src/main/java/org/zerock/wego/service/common/CommentService.java
  src/main/java/org/zerock/wego/service/party/PartyService.java
  src/main/java/org/zerock/wego/service/review/ReviewService.java
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/comment/load.jsp
  src/main/webapp/WEB-INF/views/comment/reply.jsp
  src/main/webapp/WEB-INF/views/party/detail.jsp
  src/main/webapp/WEB-INF/views/review/detail.jsp
  src/main/webapp/resources/js/comment.js
  src/main/webapp/resources/js/delete.js
  src/main/webapp/resources/js/review-detail.js
Labels: 백엔드, 🎉FEAT, 🛠 Refactoring

#101 <refactor, fix, feat> : 댓글 로딩 버그 수정, 댓글 수정 버그 수정, 글 삭제시 관련 데이터 삭제작업 추가, 댓글 로직 약간 수정
  src/main/java/org/zerock/wego/aop/LogAdvice.java
  src/main/java/org/zerock/wego/controller/CommentController.java
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/controller/ReviewController.java
  src/main/java/org/zerock/wego/domain/party/PartyViewVO.java
  src/main/java/org/zerock/wego/mapper/CommentMapper.java
  src/main/java/org/zerock/wego/service/common/CommentService.java
  src/main/java/org/zerock/wego/service/party/PartyService.java
  src/main/java/org/zerock/wego/service/review/ReviewService.java
  src/main/resources/org/zerock/wego/mapper/CommentMapper.xml
  src/main/resources/org/zerock/wego/mapper/ReviewMapper.xml
  src/main/webapp/WEB-INF/views/comment/comment.jsp
  src/main/webapp/WEB-INF/views/comment/load.jsp
  src/main/webapp/WEB-INF/views/party/detail.jsp
  src/main/webapp/resources/js/comment.js
  src/main/webapp/resources/js/delete.js
  src/main/webapp/resources/js/review-detail.js
Labels: 👾버그, 백엔드, 🎉FEAT, 🛠 Refactoring

#102 fix : haeder, ranking관련 css 파일 수정
  src/main/webapp/resources/css/default.css
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/ranking-detail.css
  src/main/webapp/resources/css/ranking.css
Labels: 👾버그, UI

#103 <refactor> : 후기/모집글 상세페이지 css 수정 default.css 제거
  src/main/webapp/resources/css/party-detail.css
  src/main/webapp/resources/css/review-detail.css
Labels: 🖼프론트엔드

#104 feat, refactor : 파일 서비스 관련 리팩터링 및 파일 조회시 순서 정렬 추가
  src/main/java/org/zerock/wego/service/common/FileService.java
  src/main/resources/org/zerock/wego/mapper/FileMapper.xml
Labels: 백엔드, 🎉FEAT, 🖼프론트엔드, 🛠 Refactoring

#105 feat : 모집 글 등록 시 join_tb에 반영되도록 추가
  src/main/java/org/zerock/wego/controller/PartyController.java
Labels: 백엔드, 🎉FEAT, 🖼프론트엔드, ✨중요

#108 feat, refactor, fix : 통합검색페이지(더보기) 기능 추가 및 Mapper.xml 리팩터링, FileService 수정 등
  src/main/java/org/zerock/wego/controller/FavoriteController.java
  src/main/java/org/zerock/wego/controller/SearchController.java
  src/main/java/org/zerock/wego/domain/common/FavoriteDTO.java
  src/main/java/org/zerock/wego/service/common/FileService.java
  src/main/resources/org/zerock/wego/mapper/FavoriteMapper.xml
  src/main/resources/org/zerock/wego/mapper/FileMapper.xml
  src/main/resources/org/zerock/wego/mapper/PartyMapper.xml
  src/main/resources/org/zerock/wego/mapper/ReviewMapper.xml
  src/main/resources/org/zerock/wego/mapper/SanInfoMapper.xml
  src/main/webapp/WEB-INF/views/search.jsp
  src/main/webapp/resources/js/favorite.js
  src/main/webapp/resources/js/header.js
Labels: 백엔드, 🎉FEAT, 🖼프론트엔드, 🛠 Refactoring, 🔍Review Required, ✨중요

#109 feat: 알림기능을 추가합니다.
  pom.xml
  src/main/java/org/zerock/wego/controller/NotificationController.java
  src/main/java/org/zerock/wego/domain/common/FavoriteVO.java
  src/main/java/org/zerock/wego/domain/common/NotificationDTO.java
  src/main/java/org/zerock/wego/domain/common/NotificationVO.java
  src/main/java/org/zerock/wego/mapper/NotificationMapper.java
  src/main/java/org/zerock/wego/service/common/CommentService.java
  src/main/java/org/zerock/wego/service/common/FavoriteService.java
  src/main/java/org/zerock/wego/service/common/NotificationService.java
  src/main/java/org/zerock/wego/service/common/UserService.java
  src/main/java/org/zerock/wego/socket/NotificationWebSocketHandler.java
  src/main/resources/org/zerock/wego/mapper/NotificationMapper.xml
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/common/notification.jsp
  src/main/webapp/WEB-INF/views/profile/userpage.jsp
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/notification.css
  src/main/webapp/resources/img/notification-bell.png
  src/main/webapp/resources/img/yellowBadge.png
  src/main/webapp/resources/img/꽃카.jpg
  src/main/webapp/resources/js/notification.js
  src/main/webapp/resources/js/toggle.js
  src/main/webapp/resources/svg/badgeset.png
Labels: 🎉FEAT, 🖼프론트엔드, 🔍Review Required, ✨중요

#110 <refactor> : ModelAndView -> Model + String 변경
  src/main/java/org/zerock/wego/controller/CommentController.java
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/controller/ReportController.java
  src/main/java/org/zerock/wego/controller/ReviewController.java
  src/main/java/org/zerock/wego/mapper/JoinMapper.java
  src/main/java/org/zerock/wego/mapper/ReportMapper.java
  src/main/java/org/zerock/wego/service/common/CommentService.java
  src/main/java/org/zerock/wego/service/common/ReportService.java
  src/main/java/org/zerock/wego/service/party/JoinService.java
  src/main/java/org/zerock/wego/service/party/PartyService.java
  src/main/java/org/zerock/wego/service/review/ReviewService.java
  src/main/resources/org/zerock/wego/mapper/CommentMapper.xml
  src/main/resources/org/zerock/wego/mapper/ReportMapper.xml
  src/main/webapp/WEB-INF/views/party/detail.jsp
  src/main/webapp/WEB-INF/views/review/detail.jsp
  src/main/webapp/resources/css/review-detail.css
  src/main/webapp/resources/js/comment.js
Labels: 🎉FEAT, 🖼프론트엔드, 🛠 Refactoring

#111 <feat><fix>마이페이지 코드수정 및 기능추가
  src/main/java/org/zerock/wego/controller/ProfileController.java
  src/main/java/org/zerock/wego/domain/common/UserDTO.java
  src/main/java/org/zerock/wego/mapper/ProfileMapper.java
  src/main/java/org/zerock/wego/service/profile/ProfileService.java
  src/main/resources/org/zerock/wego/mapper/ProfileMapper.xml
  src/main/webapp/WEB-INF/views/mypage/availableParty.jsp
  src/main/webapp/WEB-INF/views/mypage/footer.jsp
  src/main/webapp/WEB-INF/views/mypage/head.jsp
  src/main/webapp/WEB-INF/views/mypage/header.jsp
  src/main/webapp/WEB-INF/views/mypage/myComment.jsp
  src/main/webapp/WEB-INF/views/mypage/myLike.jsp
  src/main/webapp/WEB-INF/views/mypage/myPost.jsp
  src/main/webapp/WEB-INF/views/mypage/myclimb.jsp
  src/main/webapp/WEB-INF/views/mypage/myinfo.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
  src/main/webapp/WEB-INF/views/mypage/mypageContainer.jsp
  src/main/webapp/WEB-INF/views/mypage/mytext.html
  src/main/webapp/WEB-INF/views/mypage/mytext.jsp
  src/main/webapp/WEB-INF/views/mypage/nickname.jsp
  src/main/webapp/WEB-INF/views/mypage/pastParty.jsp
  src/main/webapp/resources/css/myPageindex.css
  src/main/webapp/resources/css/myinfo.css
  src/main/webapp/resources/css/userpageindex.css
  src/main/webapp/resources/js/myinfo.js
  src/main/webapp/resources/js/mypage.js
Labels: 👾버그, 🖼프론트엔드

#112 <refactor> : (소소한pr) 참여여부 확인 수정, 채팅 구현 중
  src/main/java/org/zerock/wego/controller/CommentController.java
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/controller/ReviewController.java
  src/main/java/org/zerock/wego/domain/chat/ChatDTO.java
  src/main/java/org/zerock/wego/domain/chat/ChatRoomDTO.java
  src/main/java/org/zerock/wego/domain/chat/ChatRoomVO.java
  src/main/java/org/zerock/wego/domain/chat/ChatVO.java
  src/main/java/org/zerock/wego/interceptor/PostInterceptor.java
  src/main/java/org/zerock/wego/service/party/JoinService.java
  src/main/java/org/zerock/wego/service/party/PartyService.java
  src/main/java/org/zerock/wego/service/review/ReviewService.java
  src/main/webapp/WEB-INF/views/party/detail.jsp
  src/main/webapp/resources/css/comment.css
  src/main/webapp/resources/js/review-detail.js
Labels: 🖼프론트엔드, 🛠 Refactoring

#113 refactor , fix: String 리턴 + Model 로 수정, 예외추가 및 짜잘짜잘한 수정
  src/main/java/org/zerock/wego/controller/BadgeController.java
  src/main/java/org/zerock/wego/controller/LoginController.java
  src/main/java/org/zerock/wego/controller/ReviewController.java
  src/main/java/org/zerock/wego/exception/LoginException.java
  src/main/java/org/zerock/wego/mapper/BadgeGetMapper.java
  src/main/java/org/zerock/wego/mapper/UserMapper.java
  src/main/java/org/zerock/wego/service/badge/BadgeGetService.java
  src/main/java/org/zerock/wego/service/common/FileService.java
  src/main/java/org/zerock/wego/service/common/UserService.java
  src/main/java/org/zerock/wego/service/oauth/LoginService.java
  src/main/java/org/zerock/wego/service/oauth/OAuthService.java
  src/main/resources/org/zerock/wego/mapper/BadgeGetMapper.xml
  src/main/resources/org/zerock/wego/mapper/UserMapper.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/badge/badge.jsp
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/WEB-INF/views/mypage/head.jsp
  src/main/webapp/WEB-INF/views/ranking/detail.jsp
  src/main/webapp/resources/js/badge.js
Labels: 백엔드, 🛠 Refactoring, ✨중요
