Repository KH-Q-peaker/project-wego, pull requests merged in 2023-05, with the labels that each got.

#114 <feat, refactor> : 모집글 채팅 기능 추가, "__AUTH__" 변경
  src/main/java/org/zerock/wego/config/ChatWebSocketConfig.java
  src/main/java/org/zerock/wego/controller/ChatController.java
  src/main/java/org/zerock/wego/controller/CommentController.java
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/controller/ReportController.java
  src/main/java/org/zerock/wego/controller/ReviewController.java
  src/main/java/org/zerock/wego/domain/chat/ChatRoomVO.java
  src/main/java/org/zerock/wego/interceptor/ChatRoomInterceptor.java
  src/main/java/org/zerock/wego/mapper/ChatMapper.java
  src/main/java/org/zerock/wego/mapper/CommentMapper.java
  src/main/java/org/zerock/wego/mapper/JoinMapper.java
  src/main/java/org/zerock/wego/service/common/ChatService.java
  src/main/java/org/zerock/wego/service/common/CommentService.java
  src/main/java/org/zerock/wego/service/party/JoinService.java
  src/main/java/org/zerock/wego/socket/ChatWebSocketHandler.java
  src/main/resources/org/zerock/wego/mapper/ChatMapper.xml
  src/main/resources/org/zerock/wego/mapper/CommentMapper.xml
  src/main/resources/org/zerock/wego/mapper/JoinMapper.xml
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/chat/room.jsp
  src/main/webapp/WEB-INF/views/party/detail.jsp
  src/main/webapp/WEB-INF/views/review/detail.jsp
  src/main/webapp/resources/css/chat.css
  src/main/webapp/resources/css/comment.css
  src/main/webapp/resources/css/review-detail.css
  src/main/webapp/resources/js/chat.js
  src/main/webapp/resources/js/comment.js
  src/main/webapp/resources/js/delete.js
  src/main/webapp/resources/js/scroll.js
Labels: 백엔드, 🎉FEAT, 🖼프론트엔드, 🛠 Refactoring, ✨중요

#115 ﻿<refactor> 알림 리뷰 반영해서 수정하고 댓글 알림시 해당 댓글내용 반영되게 하였습니다.
  src/main/java/org/zerock/wego/controller/NotificationController.java
  src/main/java/org/zerock/wego/domain/common/NotificationVO.java
  src/main/java/org/zerock/wego/mapper/NotificationMapper.java
  src/main/java/org/zerock/wego/service/common/NotificationService.java
  src/main/resources/org/zerock/wego/mapper/NotificationMapper.xml
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/common/notification.jsp
  src/main/webapp/resources/js/notification.js
Labels: 🛠 Refactoring

#116 <refactor> : ChatRoom, Join 에서 status 컬럼 제거로 인한 매퍼와 서비스 수정
  src/main/java/org/zerock/wego/config/ChatWebSocketConfig.java
  src/main/java/org/zerock/wego/domain/chat/ChatRoomDTO.java
  src/main/java/org/zerock/wego/domain/chat/ChatRoomVO.java
  src/main/resources/org/zerock/wego/mapper/ChatMapper.xml
  src/main/resources/org/zerock/wego/mapper/JoinMapper.xml
  src/main/webapp/resources/js/scroll.js
Labels: 🛠 Refactoring, 🛢인프라

#117 <feat> 긴급알림기능추가
  src/main/java/org/zerock/wego/mapper/JoinMapper.java
  src/main/java/org/zerock/wego/mapper/NotificationMapper.java
  src/main/java/org/zerock/wego/service/badge/BadgeGetService.java
  src/main/java/org/zerock/wego/service/party/PartyService.java
  src/main/resources/org/zerock/wego/mapper/JoinMapper.xml
  src/main/resources/org/zerock/wego/mapper/NotificationMapper.xml
  src/main/webapp/WEB-INF/views/common/notification.jsp
  src/main/webapp/resources/css/notification.css
Labels: 🎉FEAT, 🖼프론트엔드, 🛠 Refactoring

#118 fix, refactor : review-register.css 수정, SearchService의 메소드명 일부 수정
  src/main/java/org/zerock/wego/controller/SearchController.java
  src/main/java/org/zerock/wego/service/common/SearchService.java
  src/main/webapp/resources/css/review-register.css
Labels: 백엔드, 🖼프론트엔드, 🛠 Refactoring, UI

#119 <feat> 문의하기 클릭시 네이버 SMTP로 문의 메일보내기
  pom.xml
  src/main/java/org/zerock/wego/controller/sendEmail.java
  src/main/java/org/zerock/wego/domain/common/MailDTO.java
  src/main/java/org/zerock/wego/mapper/NotificationMapper.java
  src/main/java/org/zerock/wego/service/common/NotificationService.java
  src/main/java/org/zerock/wego/smtp/NaverSMTP.java
  src/main/java/org/zerock/wego/socket/NotificationWebSocketHandler.java
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/views/common/EmailSendMain.jsp
  src/main/webapp/WEB-INF/views/common/MailForm.html
  src/main/webapp/WEB-INF/views/common/SendProcess.jsp
  src/main/webapp/WEB-INF/views/common/header.jsp
Labels: 백엔드, 🎉FEAT

#120 fix : DB수정에 따른 badge 수정, 짜잘한 프론트 수정
  src/main/java/org/zerock/wego/controller/BadgeController.java
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/domain/badge/BadgeGetDTO.java
  src/main/java/org/zerock/wego/domain/badge/BadgeGetVO.java
  src/main/java/org/zerock/wego/domain/badge/BadgeVO.java
  src/main/webapp/WEB-INF/views/badge/badge.jsp
  src/main/webapp/resources/css/badge.css
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/js/badge.js
Labels: 백엔드, 🖼프론트엔드, UI, 🛢인프라, ✨중요

#121 <feat> 메뉴바 마이페이지 링크수정 및 마이페이지 수정
  src/main/java/org/zerock/wego/controller/ProfileController.java
  src/main/java/org/zerock/wego/mapper/ProfileMapper.java
  src/main/java/org/zerock/wego/service/profile/ProfileService.java
  src/main/resources/org/zerock/wego/mapper/ProfileMapper.xml
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/mypage/mypageContainer.jsp
  src/main/webapp/resources/css/myPageindex.css
Labels: 🎉FEAT, 🖼프론트엔드

#122 <refactor> 유저페이지 목록 변경
  src/main/java/org/zerock/wego/service/common/CommentService.java
  src/main/java/org/zerock/wego/service/common/FavoriteService.java
  src/main/webapp/WEB-INF/views/profile/comment.jsp
  src/main/webapp/WEB-INF/views/profile/userpage.jsp
  src/main/webapp/WEB-INF/views/profile/userposts.jsp
  src/main/webapp/resources/css/usercomment.css
  src/main/webapp/resources/css/userposts.css
Labels: 🖼프론트엔드

#123 refactor : 파일 시스템 Base 경로 수정으로 인한 이미지 참조 경로 변경
  src/main/java/org/zerock/wego/service/common/FileService.java
  src/main/webapp/WEB-INF/views/comment/comment.jsp
  src/main/webapp/WEB-INF/views/comment/load.jsp
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/common/notification.jsp
  src/main/webapp/WEB-INF/views/info/info.jsp
  src/main/webapp/WEB-INF/views/info/infoItem.jsp
  src/main/webapp/WEB-INF/views/info/infoSearch.jsp
  src/main/webapp/WEB-INF/views/info/infoSearchFail.jsp
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/WEB-INF/views/party/detail.jsp
  src/main/webapp/WEB-INF/views/party/modify.jsp
  src/main/webapp/WEB-INF/views/party/party.jsp
  src/main/webapp/WEB-INF/views/party/partySearch.jsp
  src/main/webapp/WEB-INF/views/party/partySearchFail.jsp
  src/main/webapp/WEB-INF/views/profile/userpage.jsp
  src/main/webapp/WEB-INF/views/ranking/detail.jsp
  src/main/webapp/WEB-INF/views/ranking/ranking.jsp
  src/main/webapp/WEB-INF/views/review/detail.jsp
  src/main/webapp/WEB-INF/views/review/modify.jsp
  src/main/webapp/WEB-INF/views/review/review.jsp
  src/main/webapp/WEB-INF/views/review/reviewSearch.jsp
  src/main/webapp/WEB-INF/views/review/reviewSearchFail.jsp
  src/main/webapp/WEB-INF/views/search.jsp
Labels: 🖼프론트엔드, 🛠 Refactoring, ✨중요

#125 ??? : badge 이미지 추가
  src/main/webapp/resources/img/badge-ranking.png
  src/main/webapp/resources/img/badge-san.png
  src/main/webapp/resources/img/메달1.png
  src/main/webapp/resources/img/메달2.png
  src/main/webapp/resources/img/메달3.png
  src/main/webapp/resources/img/메달4.png
  src/main/webapp/resources/img/메달5.png
Labels: 🖼프론트엔드

#126 refactor : 호출 로그 수정 및 SessionConfig 상수 사용
  src/main/java/org/zerock/wego/controller/PartyController.java
Labels: 백엔드, 🛠 Refactoring

#127 <refactor> : top 버튼 취합, comment 등록시 입력 내용 삭제 추가
  src/main/webapp/WEB-INF/views/party/detail.jsp
  src/main/webapp/WEB-INF/views/review/detail.jsp
  src/main/webapp/resources/css/chat.css
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/party-detail.css
  src/main/webapp/resources/css/remote.css
  src/main/webapp/resources/css/review-detail.css
  src/main/webapp/resources/css/top.css
  src/main/webapp/resources/js/comment.js
Labels: 🖼프론트엔드, ✨중요

#128 <refactor, feat> : 유저 상태 컬럼 추가, 활동 제한 로직 추가, 댓글/멘션 작성 통합
  src/main/java/org/zerock/wego/controller/CommentController.java
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/domain/common/CommentDTO.java
  src/main/java/org/zerock/wego/domain/common/UserVO.java
  src/main/java/org/zerock/wego/interceptor/PostInterceptor.java
  src/main/java/org/zerock/wego/mapper/UserMapper.java
  src/main/java/org/zerock/wego/service/common/ReportService.java
  src/main/java/org/zerock/wego/service/common/UserService.java
  src/main/resources/org/zerock/wego/mapper/UserMapper.xml
  src/main/webapp/resources/js/comment.js
  src/main/webapp/resources/js/delete.js
Labels: 백엔드, 🎉FEAT, 🛠 Refactoring, 🛢인프라

#129 fit:authinterceptor 수정 및 로그인 redirect수정
  .gitignore
  src/main/java/org/zerock/wego/controller/LoginController.java
  src/main/java/org/zerock/wego/interceptor/AuthInterceptor.java
Labels: ✨중요

#130 <refactor> mypage컨트롤러
  src/main/java/org/zerock/wego/controller/ProfileController.java
Labels: 🛠 Refactoring

#132 <refactor> : 후기/모집글 작성자 닉네임 url 변경, 예외처리 변경
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/controller/ReviewController.java
  src/main/java/org/zerock/wego/interceptor/PostInterceptor.java
  src/main/java/org/zerock/wego/service/party/PartyService.java
  src/main/java/org/zerock/wego/service/review/ReviewService.java
  src/main/webapp/WEB-INF/views/party/detail.jsp
  src/main/webapp/WEB-INF/views/review/detail.jsp
  src/main/webapp/resources/js/delete.js
Labels: 백엔드, 🛠 Refactoring

#133 <style> 코드포멧팅 & mypage script js파일에 옮기기
  src/main/webapp/WEB-INF/views/mypage/availableParty.jsp
  src/main/webapp/WEB-INF/views/mypage/myComment.jsp
  src/main/webapp/WEB-INF/views/mypage/myPost.jsp
  src/main/webapp/WEB-INF/views/mypage/myinfo.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
  src/main/webapp/WEB-INF/views/mypage/mypageContainer.jsp
  src/main/webapp/WEB-INF/views/mypage/pastParty.jsp
  src/main/webapp/WEB-INF/views/profile/comment.jsp
  src/main/webapp/WEB-INF/views/profile/userpage.jsp
  src/main/webapp/WEB-INF/views/profile/userposts.jsp
  src/main/webapp/resources/js/my-available-party.js
  src/main/webapp/resources/js/my-past-party.js
  src/main/webapp/resources/js/mycomment.js
  src/main/webapp/resources/js/myinfo.js
  src/main/webapp/resources/js/mypage.js
  src/main/webapp/resources/js/mypost.js
  src/main/webapp/resources/js/user-comment.js
  src/main/webapp/resources/js/user-posts.js
  src/main/webapp/resources/js/userpage.js
Labels: 🖼프론트엔드

#134 feat, fix, refactor : 후기 글 등록 시 뱃지 추가 / 파일 업로드 경로 수정 / 좋아요 구현 수정
  src/main/java/org/zerock/wego/controller/FavoriteController.java
  src/main/java/org/zerock/wego/controller/ReviewController.java
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/resources/js/favorite.js
Labels: 백엔드, 🎉FEAT, 🖼프론트엔드, 🛠 Refactoring, 🛢인프라, ✨중요

#135 <refactor> : 웹소켓 url 수정 (contextPath 추가 )
  src/main/java/org/zerock/wego/config/ChatWebSocketConfig.java
  src/main/java/org/zerock/wego/controller/ChatController.java
  src/main/webapp/WEB-INF/views/chat/room.jsp
Labels: 🛠 Refactoring

#136 <fix> : aws ip 숨김, header 경로 수정
  src/main/java/org/zerock/wego/oauth/GoogleOAuth.java
  src/main/java/org/zerock/wego/oauth/KakaoOAuth.java
  src/main/java/org/zerock/wego/oauth/NaverOAuth.java
  src/main/webapp/WEB-INF/views/badge/badge.jsp
  src/main/webapp/WEB-INF/views/common/header.jsp
Labels: 👾버그, 백엔드, 🖼프론트엔드, UI, ✨중요

#137 fix : 통합검색결과 게시글의 상세페이지 이동 경로 수정 및 세션 만료 시 로그인 페이지로 이동 처리(모집, 후기, 좋아요)
  src/main/webapp/WEB-INF/views/search.jsp
  src/main/webapp/resources/js/favorite.js
  src/main/webapp/resources/js/party-register.js
  src/main/webapp/resources/js/review-register.js
Labels: 👾버그, 🖼프론트엔드, ✨중요

#138 <fix> 뱃지알림54개생성 버그 정리
  src/main/java/org/zerock/wego/service/badge/BadgeGetService.java
  src/main/java/org/zerock/wego/service/common/FavoriteService.java
  src/main/resources/org/zerock/wego/mapper/NotificationMapper.xml
  src/main/webapp/WEB-INF/views/common/notification.jsp
  src/main/webapp/resources/css/notification.css
Labels: 👾버그, 백엔드

#139 <feat><style>유저페이지/마이페이지 jsp 수정 및 탈퇴 구현 ing
  src/main/java/org/zerock/wego/controller/ProfileController.java
  src/main/java/org/zerock/wego/mapper/WithdrawMapper.java
  src/main/java/org/zerock/wego/service/common/WithdrawService.java
  src/main/resources/org/zerock/wego/mapper/WithdrawMapper.xml
  src/main/webapp/WEB-INF/views/mypage/myComment.jsp
  src/main/webapp/WEB-INF/views/mypage/myPost.jsp
  src/main/webapp/WEB-INF/views/profile/comment.jsp
  src/main/webapp/WEB-INF/views/profile/userpage.jsp
  src/main/webapp/WEB-INF/views/profile/userposts.jsp
  src/main/webapp/resources/css/userposts.css
Labels: 🎉FEAT

#140 <fix> userpage도 푸터고정
  src/main/java/org/zerock/wego/mapper/NotificationMapper.java
  src/main/java/org/zerock/wego/service/common/CommentService.java
  src/main/java/org/zerock/wego/service/common/NotificationService.java
  src/main/resources/org/zerock/wego/mapper/NotificationMapper.xml
  src/main/webapp/WEB-INF/views/common/notification.jsp
  src/main/webapp/WEB-INF/views/profile/userpage.jsp
  src/main/webapp/resources/js/header.js
  src/main/webapp/resources/js/userpage.js
  src/test/java/org/zerock/wego/mapper/SanInfoMapperTests.java
  src/test/java/org/zerock/wego/service/SanInfoServiceTests.java
Labels: 🖼프론트엔드

#143 <refactor> : 참여 모달창 css 수정, 에러페이지 메인 경로 수정
  src/main/webapp/WEB-INF/views/comment/comment.jsp
  src/main/webapp/WEB-INF/views/comment/load.jsp
  src/main/webapp/WEB-INF/views/comment/reply.jsp
  src/main/webapp/WEB-INF/views/error/error.jsp
  src/main/webapp/resources/css/join.css
  src/main/webapp/resources/js/comment.js
  src/main/webapp/resources/js/delete.js
  src/main/webapp/resources/js/party-detail.js
Labels: 🖼프론트엔드

#145 fix, feat : 산정보 img 추가에 따른 경로 수정, 불필요한 C삭제, 테스트 로그인 계정 등록, head.jsp 추가 및 main.jsp만 적용
  src/main/java/org/zerock/wego/controller/AuthController.java
  src/main/java/org/zerock/wego/controller/LoginController.java
  src/main/java/org/zerock/wego/controller/UserController.java
  src/main/java/org/zerock/wego/oauth/KakaoOAuth.java
  src/main/java/org/zerock/wego/oauth/NaverOAuth.java
  src/main/webapp/WEB-INF/views/common/login.jsp
  src/main/webapp/WEB-INF/views/head.jsp
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/WEB-INF/views/search.jsp
  src/main/webapp/resources/img/san-info/san-info-img-sample1.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample10.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample11.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample12.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample13.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample14.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample15.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample16.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample17.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample18.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample19.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample2.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample20.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample21.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample22.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample23.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample24.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample25.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample26.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample3.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample4.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample5.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample6.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample7.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample8.jpeg
  src/main/webapp/resources/img/san-info/san-info-img-sample9.jpeg
  src/main/webapp/resources/js/userpage.js
Labels: 백엔드, 🎉FEAT, 🖼프론트엔드, UI, 🛢인프라, ✨중요

#147 <style> 마이페이지 코드 및 css 수정
  src/main/webapp/WEB-INF/views/mypage/mypageContainer.jsp
  src/main/webapp/resources/css/myPageindex.css
  src/main/webapp/resources/css/usercomment.css
Labels: 🖼프론트엔드

#148 Fix: Sort, img 경로, remote.css 삭제
  src/main/webapp/WEB-INF/views/info/info.jsp
  src/main/webapp/WEB-INF/views/info/infoItem.jsp
  src/main/webapp/WEB-INF/views/info/infoSearch.jsp
  src/main/webapp/WEB-INF/views/info/infoSearchFail.jsp
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/WEB-INF/views/party/party.jsp
  src/main/webapp/WEB-INF/views/party/partySearch.jsp
  src/main/webapp/WEB-INF/views/party/partySearchFail.jsp
  src/main/webapp/WEB-INF/views/review/review.jsp
  src/main/webapp/WEB-INF/views/review/reviewSearch.jsp
  src/main/webapp/WEB-INF/views/review/reviewSearchFail.jsp
  src/main/webapp/resources/js/infinity-scroll.js
Labels: 👾버그, 🖼프론트엔드

#151 fix, refactor : 메인페이지 산정보 게시글에 잘못 삽입된 문자열 제거 및 후기 글 auth 체크 조건문 제거
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/controller/ReviewController.java
Labels: 👾버그, 🛠 Refactoring

#152 <refactor> : 직전 pr에서 파일 누락함. js 중복 삭제
  src/main/webapp/resources/js/scroll.js
Labels: 🖼프론트엔드

#153 <feat><style> 탈퇴 구현중, 마이페이지 js 코드 수정
  src/main/java/org/zerock/wego/controller/WithdrawController.java
  src/main/java/org/zerock/wego/mapper/WithdrawMapper.java
  src/main/java/org/zerock/wego/service/common/WithdrawService.java
  src/main/resources/org/zerock/wego/mapper/WithdrawMapper.xml
  src/main/webapp/resources/js/myinfo.js
  src/main/webapp/resources/js/mypage.js
Labels: 🎉FEAT, 🖼프론트엔드

#155 fix : 세션에 사용되는 상수를 ""로 감싸서 인식 안되는 문제 해결
  src/main/java/org/zerock/wego/controller/PartyController.java
Labels: 👾버그, 백엔드, ✨중요

#156 Fix : Infinity Scroll, SanInfo Image Path
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/controller/ReviewController.java
  src/main/java/org/zerock/wego/controller/SanInfoController.java
  src/main/java/org/zerock/wego/mapper/PartyMapper.java
  src/main/java/org/zerock/wego/mapper/ReviewMapper.java
  src/main/java/org/zerock/wego/mapper/SanInfoMapper.java
  src/main/java/org/zerock/wego/service/info/SanInfoService.java
  src/main/java/org/zerock/wego/service/party/PartyService.java
  src/main/java/org/zerock/wego/service/review/ReviewService.java
  src/main/resources/org/zerock/wego/mapper/PartyMapper.xml
  src/main/resources/org/zerock/wego/mapper/ReviewMapper.xml
  src/main/resources/org/zerock/wego/mapper/SanInfoMapper.xml
  src/main/webapp/WEB-INF/views/info/info.jsp
  src/main/webapp/WEB-INF/views/info/infoSearch.jsp
  src/main/webapp/WEB-INF/views/info/infoSearchFail.jsp
  src/main/webapp/WEB-INF/views/party/party.jsp
  src/main/webapp/WEB-INF/views/party/partySearch.jsp
  src/main/webapp/WEB-INF/views/party/partySearchFail.jsp
  src/main/webapp/WEB-INF/views/review/review.jsp
  src/main/webapp/WEB-INF/views/review/reviewSearch.jsp
  src/main/webapp/WEB-INF/views/review/reviewSearchFail.jsp
  src/main/webapp/resources/js/infinity-scroll-search.js
  src/main/webapp/resources/js/infinity-scroll.js
Labels: 👾버그, 백엔드, 🖼프론트엔드

#157 <fix> 쿼리문 오류 수정
  src/main/java/org/zerock/wego/service/badge/BadgeGetService.java
  src/main/java/org/zerock/wego/service/common/NotificationService.java
Labels: 👾버그, 백엔드

#159 <fix> : badgeGetMapper @param
  src/main/java/org/zerock/wego/mapper/BadgeGetMapper.java
Labels: 👾버그, 백엔드, ✨중요

#161 refactor : 기본 이미지 경로 수정
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/WEB-INF/views/party/detail.jsp
  src/main/webapp/WEB-INF/views/party/party.jsp
  src/main/webapp/WEB-INF/views/party/partyItem.jsp
  src/main/webapp/WEB-INF/views/party/partySearch.jsp
  src/main/webapp/WEB-INF/views/party/partySearchFail.jsp
  src/main/webapp/WEB-INF/views/ranking/detail.jsp
  src/main/webapp/WEB-INF/views/ranking/ranking.jsp
  src/main/webapp/WEB-INF/views/review/review.jsp
  src/main/webapp/WEB-INF/views/review/reviewItem.jsp
  src/main/webapp/WEB-INF/views/review/reviewSearch.jsp
  src/main/webapp/WEB-INF/views/review/reviewSearchFail.jsp
  src/main/webapp/WEB-INF/views/search.jsp
  src/main/webapp/resources/css/main.css
  src/main/webapp/resources/img/default-party.jpg
  src/main/webapp/resources/img/default-review.jpg
  src/main/webapp/resources/img/default-user.jpg
Labels: 🖼프론트엔드, 🛠 Refactoring, ✨중요

#162 <feat, refactor> : 좋아요 추가, 모달 css 변경
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/controller/ReviewController.java
  src/main/resources/org/zerock/wego/mapper/FavoriteMapper.xml
  src/main/webapp/WEB-INF/views/party/detail.jsp
  src/main/webapp/resources/css/join.css
  src/main/webapp/resources/js/like.js
Labels: 🎉FEAT, 🖼프론트엔드, 🛠 Refactoring

#163 Fix: 검색실패 조건 추가, 게시물 유저 링크, 무한스크롤 오류 수정, 검색결과 범위 추가
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/java/org/zerock/wego/controller/ReviewController.java
  src/main/java/org/zerock/wego/controller/SanInfoController.java
  src/main/java/org/zerock/wego/mapper/SanInfoMapper.java
  src/main/resources/org/zerock/wego/mapper/PartyMapper.xml
  src/main/resources/org/zerock/wego/mapper/ReviewMapper.xml
  src/main/webapp/WEB-INF/views/info/info.jsp
  src/main/webapp/WEB-INF/views/info/infoItem.jsp
  src/main/webapp/WEB-INF/views/info/infoSearch.jsp
  src/main/webapp/WEB-INF/views/info/infoSearchFail.jsp
  src/main/webapp/WEB-INF/views/party/party.jsp
  src/main/webapp/WEB-INF/views/party/partyItem.jsp
  src/main/webapp/WEB-INF/views/party/partySearch.jsp
  src/main/webapp/WEB-INF/views/party/partySearchFail.jsp
  src/main/webapp/WEB-INF/views/review/review.jsp
  src/main/webapp/WEB-INF/views/review/reviewItem.jsp
  src/main/webapp/WEB-INF/views/review/reviewSearch.jsp
  src/main/webapp/WEB-INF/views/review/reviewSearchFail.jsp
  src/main/webapp/resources/css/partyItem.css
  src/main/webapp/resources/css/reviewItem.css
  src/main/webapp/resources/js/board-href.js
  src/main/webapp/resources/js/infinity-scroll-search.js
  src/main/webapp/resources/js/infinity-scroll.js
  src/main/webapp/resources/js/search-type.js
  src/main/webapp/resources/js/top.js
Labels: 👾버그, 백엔드, 🖼프론트엔드, 🛠 Refactoring, UI

#164 < fix > 정리
  src/main/java/org/zerock/wego/controller/NotificationController.java
  src/main/java/org/zerock/wego/service/common/FavoriteService.java
  src/main/java/org/zerock/wego/service/common/NotificationService.java
  src/main/java/org/zerock/wego/service/party/PartyService.java
  src/main/java/org/zerock/wego/socket/NotificationWebSocketHandler.java
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/resources/js/notification.js
Labels: 👾버그

#166 <refactor> : 상세페이지 작성자 프로필 경로변경
  src/main/webapp/WEB-INF/views/review/detail.jsp
Labels: 🖼프론트엔드

#167 fix 뱃지겟뷰 삭제로 사용테이블쿼리문바꿈
  src/main/resources/org/zerock/wego/mapper/NotificationMapper.xml
Labels: 👾버그

#169 <feat> 카카오 언링크
  src/main/java/org/zerock/wego/controller/WithdrawController.java
  src/main/java/org/zerock/wego/interceptor/AfterLoginInterceptor.java
  src/main/java/org/zerock/wego/interceptor/AuthInterceptor.java
  src/main/java/org/zerock/wego/oauth/KakaoOAuth.java
  src/main/java/org/zerock/wego/service/oauth/OAuthService.java
  src/main/webapp/resources/js/mypage.js
Labels: 🎉FEAT

#170 <refactor> : 좋아요 isExist 매퍼 추가
  src/main/java/org/zerock/wego/controller/FavoriteController.java
  src/main/java/org/zerock/wego/mapper/FavoriteMapper.java
  src/main/java/org/zerock/wego/service/common/FavoriteService.java
  src/main/resources/org/zerock/wego/mapper/FavoriteMapper.xml
  src/main/webapp/resources/js/like.js
Labels: 🛠 Refactoring

#171 refactor : 메인페이지에서 모집 및 후기 글 작성자명 ... 처리
  src/main/webapp/resources/css/main.css
Labels: 🖼프론트엔드, 🛠 Refactoring, UI

#172 <fix> 이미지 사진 경로 수정
  src/main/webapp/WEB-INF/views/common/notification.jsp
  src/main/webapp/WEB-INF/views/profile/userpage.jsp
  src/main/webapp/resources/js/notification.js
  src/main/webapp/resources/js/user-comment.js
  src/main/webapp/resources/js/user-posts.js
  src/main/webapp/resources/js/userpage.js
Labels: 👾버그, 🖼프론트엔드

#174 feat : 메인페이지에서 작성자 이미지, 작성자명 클릭 시 작성자의 프로필페이지로 이동
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/resources/css/main.css
  src/main/webapp/resources/js/favorite.js
Labels: 🎉FEAT, 🖼프론트엔드, ✨중요

#175 <feat> 탈퇴 js,css 수정
  src/main/webapp/WEB-INF/views/mypage/availableParty.jsp
  src/main/webapp/WEB-INF/views/mypage/myComment.jsp
  src/main/webapp/WEB-INF/views/mypage/myPost.jsp
  src/main/webapp/WEB-INF/views/mypage/mypageContainer.jsp
  src/main/webapp/WEB-INF/views/mypage/pastParty.jsp
  src/main/webapp/WEB-INF/views/profile/comment.jsp
  src/main/webapp/WEB-INF/views/profile/userposts.jsp
  src/main/webapp/resources/css/myPageindex.css
  src/main/webapp/resources/css/myinfo.css
  src/main/webapp/resources/css/mypage.css
  src/main/webapp/resources/js/my-available-party.js
  src/main/webapp/resources/js/my-past-party.js
  src/main/webapp/resources/js/mycomment.js
  src/main/webapp/resources/js/myinfo.js
  src/main/webapp/resources/js/mypage.js
  src/main/webapp/resources/js/mypost.js
Labels: 🎉FEAT

#176 <Fix, style, feat> 무한스크롤 버그 수정, 좋아요 서비스 수정, 산정보글 좋아요 기능 추가, 게시판 css 변경
  src/main/java/org/zerock/wego/service/common/FavoriteService.java
  src/main/webapp/WEB-INF/views/info/detail.jsp
  src/main/webapp/resources/css/partyItem.css
  src/main/webapp/resources/css/reviewItem.css
  src/main/webapp/resources/js/favorite-info-detail.js
  src/main/webapp/resources/js/infinity-scroll-search.js
  src/main/webapp/resources/js/infinity-scroll.js
Labels: 백엔드, 🎉FEAT, 🖼프론트엔드, 🛠 Refactoring

#177 <fix> : Main ranking 수정, 계속해서 인포 수정중
  src/main/java/org/zerock/wego/domain/openweather/Daily.java
  src/main/java/org/zerock/wego/domain/openweather/Hourly.java
  src/main/webapp/WEB-INF/views/info/food.jsp
  src/main/webapp/WEB-INF/views/info/weather.jsp
  src/main/webapp/resources/css/ranking.css
  src/main/webapp/resources/css/sanInfo-detail.css
  src/main/webapp/resources/css/sanInfo-weather.css
Labels: 백엔드, 🎉FEAT, ✨중요

#178 <refactor> : 후기 상세페이지 작성자 프사 경로 변경
  src/main/webapp/WEB-INF/views/common/join.jsp
  src/main/webapp/WEB-INF/views/review/detail.jsp
Labels: 🖼프론트엔드

#180 <feat> : 카카오 맵 - 주변식당 지도 추가
  src/main/webapp/WEB-INF/views/info/detail.jsp
  src/main/webapp/WEB-INF/views/info/food.jsp
  src/main/webapp/resources/css/sanInfo-food.css
  src/main/webapp/resources/js/comment.js
  src/main/webapp/resources/js/sanInfo-food.js
Labels: 🎉FEAT, 🖼프론트엔드

#181 fix : ranking.jsp에서 불필요한 class 속성 제거 및 모집 글에 사진이 없는 상태에서 추가 시 에러발생 현상 수정
  src/main/java/org/zerock/wego/controller/PartyController.java
  src/main/webapp/WEB-INF/views/ranking/ranking.jsp
Labels: 👾버그

#182 <style>탈퇴 코드수정 및 마이페이지 뱃지 css 수정
  src/main/java/org/zerock/wego/controller/ProfileController.java
  src/main/java/org/zerock/wego/controller/WithdrawController.java
  src/main/java/org/zerock/wego/mapper/WithdrawMapper.java
  src/main/java/org/zerock/wego/oauth/NaverOAuth.java
  src/main/java/org/zerock/wego/service/common/WithdrawService.java
  src/main/java/org/zerock/wego/service/oauth/OAuthService.java
  src/main/resources/org/zerock/wego/mapper/WithdrawMapper.xml
  src/main/webapp/resources/css/myPageindex.css
  src/main/webapp/resources/css/userpageindex.css
  src/main/webapp/resources/js/mypage.js
  src/main/webapp/resources/js/user-comment.js
  src/main/webapp/resources/js/user-posts.js
Labels: 🖼프론트엔드

#183 <fix> 마이페이지 푸터 고정, 알림이미지경로변경
  src/main/java/org/zerock/wego/config/NotificationConfig.java
  src/main/java/org/zerock/wego/controller/NotificationController.java
  src/main/java/org/zerock/wego/service/common/NotificationService.java
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/views/common/notification.jsp
  src/main/webapp/resources/js/mypage.js
  src/main/webapp/resources/js/notification.js
  src/main/webapp/resources/js/userpage.js
Labels: 👾버그, 백엔드, 🖼프론트엔드

#184 Fix, Style: Sort ajax 수정, 게시판 모바일 스타일 수정
  src/main/webapp/resources/css/partyFrame.css
  src/main/webapp/resources/css/partySearch.css
  src/main/webapp/resources/css/reviewFrame.css
  src/main/webapp/resources/css/reviewSearch.css
  src/main/webapp/resources/css/sanInfoFrame.css
  src/main/webapp/resources/css/sanInfoSearch.css
  src/main/webapp/resources/js/infinity-scroll.js
Labels: 👾버그, 🖼프론트엔드, UI

#185 Update README.md
  README.md
Labels: 📝Docs

#189 fix : 사용자의 등록 이미지가 없을 때 기본이미지가 출력되지 않는 현상 수정
  src/main/webapp/WEB-INF/views/mypage/mypageContainer.jsp
Labels: 👾버그, 🖼프론트엔드, ✨중요

#195 <refactor> : join join join 사진 변경
  src/main/webapp/WEB-INF/views/common/join.jsp
Labels: 🖼프론트엔드

#197 <refactor> : 제발 최종
  src/main/webapp/WEB-INF/views/comment/comment.jsp
  src/main/webapp/WEB-INF/views/comment/load.jsp
Labels: 🖼프론트엔드

#199 <docs> 리드미 수정합니다.
  README.md
Labels: 📝Docs

#201 <fix> : README 최종 수정
  README.md
  etc/wego-code-convention.pdf
  etc/wego-erd.pdf
  etc/wego-plan.pdf
  src/main/webapp/WEB-INF/spring/root-context.xml
  test
  ✅feature.md
  👾-bug-.md
Labels: 📝Docs
